### ISSUE TITLE
testes certos só que não

### ISSUE THREAD

**Issue by mdgf1** [diogotcorreia/kanban-iaed-tests#16]
Tive um teste que magicamente me deu correto porque chegava a uma certa linha e o meu programa parava, mas até aquela linha não existiam diferenças n sei bem como resolver isso just saying, para alem disso o file diff desse teste esta vazio por isso penso que estejam a ver se os testes estão passados se o diff está vazio ou não, acho que se for isso basta comparar o length do meu output contra o vosso mas não sei

**Comment by diogotcorreia** [comment]
O programa `diff` compara ambos os outputs, não compara só até onde um deles vai.
Se o teu programa parar a meio (e.g. ficar num loop infinito), o teste não deve terminar suponho eu. Se ele terminar mais cedo do que o suposto, o diff vai reparar.
Experimenta usar o makefile se estás a usar o script do Rafael.

**Comment by mdgf1** [comment]
sry tens razão acho que me tinha enganado em alguma coisa quando repeti manualmente ja deu bem
