### ISSUE TITLE
Erros no output nos testes ct004 e ct005

### ISSUE THREAD

**Issue by DavidYeet123** [diogotcorreia/kanban-iaed-tests#22]
Quando uma tarefa esta em TO DO e executa se o comando m [id da tarefa em questao] [user] TO DO, isto nao deve fazer absolutamente nada segundo o professor, e quando submeti o codigo com esta alteracao estava correto.

**Comment by diogotcorreia** [comment]
Esses testes já foram atualizados há uns dias, faz git pull.
