### ISSUE TITLE
Passa todos os testes, mas dá SIGSEV em 9 no Mooshak

### ISSUE THREAD

**Issue by Nuno-Dev** [diogotcorreia/kanban-iaed-tests#23]
Boas, antes de mais, muito obrigado pelos testes, ajudaram bastante!
Tenho uma dúvida, ele passa todos os testes, ct001 até ao ct012, sem diferenças dos .out, porém no Mooshak aparece-me isto:

![image](https://user-images.githubusercontent.com/57804241/114271038-6717e580-9a07-11eb-9059-f383d3b81170.png)

alguma ideia do que poderá ser?

**Comment by diogotcorreia** [comment]
Not really.
Tentamos fazer os testes o melhor possível, mas nem sempre é possível ter a mesma test coverage que o mooshak :(

O melhor para tentares perceber esses casos é ires experimentando comandos manualmente. Provavelmente consegues chegar lá de forma simples.

Pergunta também no discord por esses testes, há malta que já tem ideia do que são.

Verifica se tens algum vetor que não tem o tamanho certo (embora pouco provável porque os testes comunitários testam isso).
Tenta correr com o `valgrind`, pois pode-te avisar de variáveis não inicializadas mesmo que o programa funcione.
```bash
valgrind ./proj1 < path/to/ct004.in > /dev/null
```

(o `> /dev/null` é para ignorar o output)

**Comment by Nuno-Dev** [comment]
Obrigado!!
